/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mapnik_Query */

#ifndef _Included_mapnik_Query
#define _Included_mapnik_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mapnik_Query
 * Method:    alloc
 * Signature: (Lmapnik/Box2d;DDD)J
 */
JNIEXPORT jlong JNICALL Java_mapnik_Query_alloc
  (JNIEnv *, jclass, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     mapnik_Query
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mapnik_Query_dealloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mapnik_Query
 * Method:    addPropertyName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mapnik_Query_addPropertyName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
