/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mapnik_Parameters */

#ifndef _Included_mapnik_Parameters
#define _Included_mapnik_Parameters
#ifdef __cplusplus
extern "C" {
#endif
#undef mapnik_Parameters_serialVersionUID
#define mapnik_Parameters_serialVersionUID 362498820763181265i64
#undef mapnik_Parameters_DEFAULT_INITIAL_CAPACITY
#define mapnik_Parameters_DEFAULT_INITIAL_CAPACITY 16L
#undef mapnik_Parameters_MAXIMUM_CAPACITY
#define mapnik_Parameters_MAXIMUM_CAPACITY 1073741824L
#undef mapnik_Parameters_DEFAULT_LOAD_FACTOR
#define mapnik_Parameters_DEFAULT_LOAD_FACTOR 0.75f
#undef mapnik_Parameters_TREEIFY_THRESHOLD
#define mapnik_Parameters_TREEIFY_THRESHOLD 8L
#undef mapnik_Parameters_UNTREEIFY_THRESHOLD
#define mapnik_Parameters_UNTREEIFY_THRESHOLD 6L
#undef mapnik_Parameters_MIN_TREEIFY_CAPACITY
#define mapnik_Parameters_MIN_TREEIFY_CAPACITY 64L
/*
 * Class:     mapnik_Parameters
 * Method:    setNativeInt
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_mapnik_Parameters_setNativeInt
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     mapnik_Parameters
 * Method:    setNativeString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mapnik_Parameters_setNativeString
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     mapnik_Parameters
 * Method:    setNativeDouble
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_mapnik_Parameters_setNativeDouble
  (JNIEnv *, jclass, jlong, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
