/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mapnik_FreetypeEngine */

#ifndef _Included_mapnik_FreetypeEngine
#define _Included_mapnik_FreetypeEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mapnik_FreetypeEngine
 * Method:    registerFont
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mapnik_FreetypeEngine_registerFont
  (JNIEnv *, jclass, jstring);

/*
 * Class:     mapnik_FreetypeEngine
 * Method:    registerFonts
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_mapnik_FreetypeEngine_registerFonts
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     mapnik_FreetypeEngine
 * Method:    isFontFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mapnik_FreetypeEngine_isFontFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     mapnik_FreetypeEngine
 * Method:    faceNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_mapnik_FreetypeEngine_faceNames
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
