/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mapnik_Renderer */

#ifndef _Included_mapnik_Renderer
#define _Included_mapnik_Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mapnik_Renderer
 * Method:    renderAgg
 * Signature: (Lmapnik/MapDefinition;Lmapnik/Image;DII)V
 */
JNIEXPORT void JNICALL Java_mapnik_Renderer_renderAgg
  (JNIEnv *, jclass, jobject, jobject, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
