/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mapnik_Geometry */

#ifndef _Included_mapnik_Geometry
#define _Included_mapnik_Geometry
#ifdef __cplusplus
extern "C" {
#endif
#undef mapnik_Geometry_TYPE_POINT
#define mapnik_Geometry_TYPE_POINT 1L
#undef mapnik_Geometry_TYPE_LINESTRING
#define mapnik_Geometry_TYPE_LINESTRING 2L
#undef mapnik_Geometry_TYPE_POLYGON
#define mapnik_Geometry_TYPE_POLYGON 3L
#undef mapnik_Geometry_TYPE_MULTIPOINT
#define mapnik_Geometry_TYPE_MULTIPOINT 4L
#undef mapnik_Geometry_TYPE_MULTILINESTRING
#define mapnik_Geometry_TYPE_MULTILINESTRING 5L
#undef mapnik_Geometry_TYPE_MULTIPOLYGON
#define mapnik_Geometry_TYPE_MULTIPOLYGON 6L
/*
 * Class:     mapnik_Geometry
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mapnik_Geometry_getType
  (JNIEnv *, jobject);

/*
 * Class:     mapnik_Geometry
 * Method:    getNumPoints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mapnik_Geometry_getNumPoints
  (JNIEnv *, jobject);

/*
 * Class:     mapnik_Geometry
 * Method:    getVertex
 * Signature: (ILmapnik/Coord;)I
 */
JNIEXPORT jint JNICALL Java_mapnik_Geometry_getVertex
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     mapnik_Geometry
 * Method:    getEnvelope
 * Signature: ()Lmapnik/Box2d;
 */
JNIEXPORT jobject JNICALL Java_mapnik_Geometry_getEnvelope
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
